{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "srengine.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srengine.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
